apiVersion: v1
kind: Service
metadata:
  name: "python-service"
  namespace: {{ .Values.global.namespace }}
  labels:
    app: "python-deployment"
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
    name: http
  # - port: 443
  #   targetPort: 443
  #   name: https
  selector:
    app: "python-deployment"