image: docker:18.09.7

stages:
  - deploy

services:
- docker:18.09.7-dind

variables:
  K8S_STABLE_VERSION_URL: https://storage.googleapis.com/kubernetes-release/release/v1.16.2/bin/linux/amd64/kubectl


before_script:
  - apk add --no-cache curl
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - mv ./kubectl /usr/local/bin/kubectl
  - mv ./bin/templater /usr/local/bin/templater
  - apk add --no-cache bash
  - apk add --no-cache openssh
  - curl -LO https://get.helm.sh/helm-v3.3.1-linux-amd64.tar.gz --output ./helm-v3.3.1-linux-amd64.tar.gz
  - tar -zxvf ./helm-v3.3.1-linux-amd64.tar.gz
  - chmod +x ./linux-amd64/helm
  - mv ./linux-amd64/helm /usr/local/bin/helm

.deploy_lifecycle: &deploy_lifecycle
  stage: deploy
  script:
    - kubectl config set-cluster k8s-cluster --server="$K8S_URL" --insecure-skip-tls-verify=true
    - kubectl config set-credentials admin --token="$K8S_TOKEN"
    - kubectl config set-context k8s-cluster --cluster=k8s-cluster --user=admin
    - kubectl config use-context k8s-cluster
    - kubectl cluster-info
    - ./deploy.sh

deploy:develop:
  <<: *deploy_lifecycle
  variables:
    SSL_ISSUER: letsencrypt-dev
    PHP_HOST: php-naren.dev.aks.linnovate.net
    PYTHON_HOST: python-naren.dev.aks.linnovate.net
    NODE_HOST: node-naren.dev.aks.linnovate.net
    NAMESPACE: naren-dev
  environment:
      name: develop
      url: https://php.dev.aks.linnovate.net
  only:
    refs:
      - master
    variables:
      - $ENV == "develop"

deploy:stage:
  <<: *deploy_lifecycle
  variables:
    SSL_ISSUER: letsencrypt-stage
    PHP_HOST: php-naren.new-aks-stage.linnovate.net
    PYTHON_HOST: python-naren.new-aks-stage.linnovate.net
    NODE_HOST: node-naren.new-aks-stage.linnovate.net
    NAMESPACE: naren-stage
  environment:
      name: stage
      url: http://php.stage.aks.linnovate.net
  only:
    refs:
      - master
    variables:
      - $ENV == "stage"

# deploy:prod:
#   <<: *deploy_lifecycle
#   variables:
#     SSL_ISSUER: letsencrypt-prod
#     PHP_HOST: php-naren.aks1.linnovate.net
#     PYTHON_HOST: python-naren.aks1.linnovate.net
#     NODE_HOST: node-naren.aks1.linnovate.net
#     NAMESPACE: naren-prod
#   environment:
#       name: production
#       url: https://php.aks1.linnovate.net
#   only:
#     refs:
#       - master
#     variables:
#       - $ENV == "production"