apiVersion: v1
kind: Service
metadata:
  name: "php-service"
  namespace: {{ .Values.global.namespace }}
  labels:
    app: "php-deployment"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    name: http
  - port: 443
    targetPort: 443
    name: https
  selector:
    app: "php-deployment"