apiVersion: v1
kind: Service
metadata:
  name: "node-service"
  namespace: {{ .Values.global.namespace }}
  labels:
    app: "node-deployment"
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  # - port: 443
  #   targetPort: 443
  #   name: https
  selector:
    app: "node-deployment"